workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.owlkimmy.doctoritup
      vars:
        EXPO_PUBLIC_DOMAIN: "doctoritup"
      node: v18
      xcode: 15.4
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Set up Expo
        script: |
          npx expo install expo-dev-client
      - name: Prebuild iOS
        script: |
          npx expo prebuild --platform ios --clean
      - name: Set up code signing
        script: |
          xcode-project use-profiles
      - name: Build iOS
        script: |
          xcode-project build-ipa \
            --workspace "ios/doctoritup.xcworkspace" \
            --scheme "doctoritup"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - App Store Connect Users
